name: NextBigBiz
favicon: null
layout_spectrum: 0.002347597386687994
typography_spectrum: 0.75319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#eb640a'
    - '#000000'
    - '#bdbdbd'
    - '#454545'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.9821282324846834
purpose: []
