name: NextBigBiz
favicon: null
layout_spectrum: 0.24276
typography_spectrum: 0.7384
title: Find the perfect brand name for your Next Big Biz!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0352e'
    - '#000000'
    - '#d1928d'
    - '#6b2724'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
